#!/usr/bin/perl
##########################################################################
# $Id$
##########################################################################
# $Log$
########################################################
## Copyright (c) 2011 Nathan Crawford
## Covered under the included MIT/X-Consortium License:
##    http://www.opensource.org/licenses/mit-license.php
## All modifications and contributions by other persons to
## this script are assumed to have been donated to the
## Logwatch project and thus assume the above copyright
## and licensing terms.  If you want to make contributions
## under your own copyright or a different license this
## must be explicitly stated in the contribution and the
## Logwatch project reserves the right to not accept such
## contributions.  If you have made significant
## contributions to this script and want to claim
## copyright please contact logwatch-devel@logwatch.org.
#########################################################

# Detail level is currently not used
$Detail = $ENV{'LOGWATCH_DETAIL_LEVEL'} || 0;

# Init counters
$FailedRuns = 0;
$SuccessfulRuns = 0;
$ResourceFailures = 0;
$DependencyFailures = 0;

while (defined($ThisLine = <STDIN>)) {
   chomp($ThisLine);
   if ( 
      ($ThisLine =~ /Using cached catalog/) or
      ($ThisLine =~ /Caching catalog for /) or
      ($ThisLine =~ /Caching node for /) or
      ($ThisLine =~ /Caught TERM; calling stop/) or
      ($ThisLine =~ /Reopening log files/) or
      ($ThisLine =~ /Starting Puppet client version /) or
      ($ThisLine =~ /Restarting with.+puppetd/) or
      ($ThisLine =~ /Caught HUP; calling restart/) or
      ($ThisLine =~ /Skipping because of failed dependencies/) or
      ($ThisLine =~ /Failed to generate additional resources/) or
      ($ThisLine =~ /Could not retrieve catalog from remote server/) or
      ($ThisLine =~ /replacing from source .+ with contents /) or
      ($ThisLine =~ /Starting catalog run/) or
      ($ThisLine =~ /Applying configuration version/) or
      ($ThisLine =~ /Loading facts in/) or
      ($ThisLine =~ /Retrieving plugin/)
   ) {
      # Ignore
   } elsif ($ThisLine =~ /Finished catalog run in [0-9]+\.[0-9]+ seconds/) {
      $SuccessfulRuns++;
   } elsif ($ThisLine =~ /skipping run/) {
      $FailedRuns++;
   } elsif ($ThisLine =~ /File\[.+\].+checksum changed/) {
      $ThisLine =~ /File\[(.+)\].+checksum changed/;
      $ChangedFiles{$1}++;
   } elsif ($ThisLine =~ /File\[.+\].+content changed/) {
      $ThisLine =~ /File\[(.+)\].+content changed/;
      $ChangedFiles{$1}++;
   } elsif ($ThisLine =~ /File\[.+\].+created/) {
      $ThisLine =~ /File\[(.+)\].+created/;
      $ChangedFiles{$1}++;
   } elsif ($ThisLine =~ /File\[.+\].+removed/) {
      $ThisLine =~ /File\[(.+)\].+removed/;
      $ChangedFiles{$1}++;
   } elsif ($ThisLine =~ /Failed to retrieve current state of resource/) {
      $ResourceFailures++;
   } elsif ($ThisLine =~ /Package\[.+\].+ensure changed/) {
      $ThisLine =~ /Package\[(.+)\].+ensure changed/;
      $ChangedPackages{$1}++;
   } elsif ($ThisLine =~ /Package\[.+\].+ensure\) created/) {
      $ThisLine =~ /Package\[(.+)\].+ensure\) created/;
      $ChangedPackages{$1}++;
   } elsif ($ThisLine =~ /Exec\[.+\].+executed successfully/) {
      $ThisLine =~ /Exec\[(.+)\].+executed successfully/;
      $ExecRuns{$1}++;
   } elsif ($ThisLine =~ /Exec\[.+\].+Triggering 'refresh' from [0-9]+ dependencies/) {
      $ThisLine =~ /Exec\[(.+)\].+Triggering 'refresh' from [0-9]+ dependencies/;
      $ExecRuns{$1}++;
   } elsif ($ThisLine =~ /Service\[.+\].+ensure changed \'.+\' to \'running\'/) {
      $ThisLine =~ /Service\[(.+)\].+ensure changed \'.+\' to \'running\'/;
      $ServiceStarts{$1}++;
   } elsif ($ThisLine =~ /Service\[.+\].+Triggering 'refresh' from [0-9]+ dependencies/) {
      $ThisLine =~ /Service\[(.+)\].+Triggering 'refresh' from [0-9]+ dependencies/;
      $ServiceStarts{$1}++;
   } elsif ($ThisLine =~ /Dependency .+\[.+\].+ has [0-9]+ failure/) {
      $DependencyFailures++;
   } else {
      # Report any unmatched entries...
      $OtherList{$ThisLine}++;
   }
}

#######################################

print "\nSuccessful runs: $SuccessfulRuns\n" if $Detail;

if ($FailedRuns > 0) {
   print "\nFailed runs: $FailedRuns\n";
}

if (keys %ChangedFiles) {
   print "\nChanged files:\n";
   foreach $ThisOne (keys %ChangedFiles) {
      print "$ThisOne: $ChangedFiles{$ThisOne} Time(s)\n";
   }
}

if (keys %ChangedPackages) {
   print "\nChanged packages:\n";
   foreach $ThisOne (keys %ChangedPackages) {
      print "$ThisOne: $ChangedPackages{$ThisOne} Time(s)\n";
   }
}

if (keys %ExecRuns) {
   print "\nExec runs:\n";
   foreach $ThisOne (keys %ExecRuns) {
      print "$ThisOne: $ExecRuns{$ThisOne} Time(s)\n";
   }
}

if (keys %ServiceStarts) {
   print "\nService starts:\n";
   foreach $ThisOne (keys %ServiceStarts) {
      print "$ThisOne: $ServiceStarts{$ThisOne} Time(s)\n";
   }
}

if ($ResourceFailures > 0) {
   print "\nResource failures: $ResourceFailures\n";
}

if ($DependencyFailures > 0) {
   print "\nDependency failures: $DependencyFailures\n";
}

if (keys %OtherList) {
   print "\n**Unmatched Entries**\n";
   foreach $ThisOne (keys %OtherList) {
      print "$ThisOne: $OtherList{$ThisOne} Time(s)\n";
   }
}

exit(0);

# vi: shiftwidth=3 tabstop=3 syntax=perl et

