#!/usr/bin/perl

##########################################################################
# $Id$
##########################################################################

#######################################################
## Copyright (c) 2013 Teemu Ikonen
## Covered under the included MIT/X-Consortium License:
##    http://www.opensource.org/licenses/mit-license.php
## All modifications and contributions by other persons to
## this script are assumed to have been donated to the
## Logwatch project and thus assume the above copyright
## and licensing terms.  If you want to make contributions
## under your own copyright or a different license this
## must be explicitly stated in the contribution an the
## Logwatch project reserves the right to not accept such
## contributions.  If you have made significant
## contributions to this script and want to claim
## copyright please contact logwatch-devel@lists.sourceforge.net.
#########################################################

my $Detail = $ENV{'LOGWATCH_DETAIL_LEVEL'} || 0;

while (defined($ThisLine = <STDIN>)) {
   chomp($ThisLine);
   if ($ThisLine =~ /^.*] start$/) {
      $Starts++;
   }
   elsif ($ThisLine =~ /^.*rsyslogd was HUPed$/) {
      $HUPs++;
   }
   else {
      # Report any unmatched entries...
      $OtherList{$ThisLine}++;
   }
}

if ($Starts and ($Detail >=10) ) {
    print "\nrsyslogd started " . $Starts . " Time(s)\n";
}

if ($HUPs and ($Detail >=10) ) {
    print "\nrsyslogd closed files " . $HUPs. " Time(s)\n";
}

if (keys %OtherList) {
   print "\n**** Unmatched entries ****\n";
   foreach $Error (keys %OtherList) {
      print "    $Error : $OtherList{$Error} Times\n";
   }
}

exit(0);

# vi: shiftwidth=3 tabstop=3 syntax=perl et
# Local Variables:
# mode: perl
# perl-indent-level: 3
# indent-tabs-mode: nil
# End:
